"""
Read in OpenTree taxonomy.csv, join it with wikidata / wikipedia data to
generate a CSV mapping OTT to various IDs, and raw popularity.
"""

import argparse
import collections
import csv
import glob
import logging
import os.path

from ..taxon_mapping_and_popularity import OTT_popularity_mapping
from ..utilities.debug_util import parse_args_and_add_logging_switch
from ..utilities.file_utils import open_file_based_on_extension

logger = logging.getLogger(__name__)


def map_wiki_info(
    source_ptrs,
    source_order,
    OTT_ptrs,
    WD_filename,
    lang,
    WP_SQL_filename,
    WP_pageviews_filenames,
):
    """
    - source_ptrs:
    - OTT_ptrs: {ott: { ott: X, sources: {} }} (generated by get_OTT_list)

    1) use the wikidata JSON dump to map identifiers from the source_ptrs structure to
    wikidata Qids, and then on to wikipedia pages
    2) if sql and pagevisits filenames are given

    Return True if popularity is mapped
    """
    logger.debug(f"Processing wikidata json dump in parallel for {lang}")
    popularity_steps = 0
    WDitems, WPnames, swap_Qs = set_wikidata(WD_filename, source_ptrs, lang)

    if WP_SQL_filename is not None:
        logger.info(f" > Adding wikipedia page sizes from {WP_SQL_filename}")
        # Can't easily parallelize this as it is gzip compressed (not a block format)
        OTT_popularity_mapping.add_pagesize_for_titles(WPnames, WP_SQL_filename)
        popularity_steps += 1

    if len(WP_pageviews_filenames) > 0:
        logger.info(f" > Adding wikipedia visit counts from {len(WP_pageviews_filenames)} files")
        set_wikipedia_pageviews(WP_pageviews_filenames, WPnames, lang)
        popularity_steps += 1

    if popularity_steps == 2:
        logger.info(" > Calculating raw popularity measures")
        tot = 0
        for WDinstance in WDitems.values():
            if WDinstance.set_raw_popularity():
                tot += 1
        logger.info(f" ✔ Raw popularity measures set on {tot} wikidata items")
    else:
        logger.info(" x Skipping popularity calculations")

    # Here we might want to multiply up some taxa, e.g. plants,
    # see https://github.com/OneZoom/OZtree/issues/130
    logger.info(" > Finding best wiki matches")
    OTT_popularity_mapping.identify_best_wikidata(OTT_ptrs, lang, source_order)

    logger.info(" > Swapping vernacular wikidata items into taxon items")
    OTT_popularity_mapping.overwrite_wd(WDitems, swap_Qs, only_if_more_popular=(popularity_steps == 2), check_lang=lang)

    logger.info(" > Supplementing ids (EOL/IPNI) with ones from wikidata")
    supplement_from_wikidata(OTT_ptrs)

    logger.info("✔ Wikidata/wikipedia data mapped")

    display_WD_ott_stats(OTT_ptrs)

    return popularity_steps == 2


def display_WD_ott_stats(OTT_ptrs):
    """
    Display some stats about OTTs coming from Wikidata
    """
    matching_otts = 0
    mismatching_otts = 0
    no_wd_otts = 0
    for ott in OTT_ptrs:
        try:
            if OTT_ptrs[ott]["rank"] == "species":
                if OTT_ptrs[ott]["wd"].get("wd_ott") is not None:
                    if ott == OTT_ptrs[ott]["wd"].wd_ott:
                        matching_otts += 1
                    else:
                        logger.debug(f"Q{OTT_ptrs[ott]['wd'].Q}: OTT {ott} does not match {OTT_ptrs[ott]['wd'].wd_ott}")
                        mismatching_otts += 1
                else:
                    no_wd_otts += 1
        except (KeyError, AttributeError):
            pass

    logger.info("✔ Stats on Wikidata OTT matching:")
    logger.info(f"    Leaves where the WD ott matches the ott: {matching_otts}")
    logger.info(f"    Leaves where the WD ott does not match the wd_ott: {mismatching_otts}")
    logger.info(f"    Leaves where WD does not have an ott: {no_wd_otts}")


def set_wikidata(bz2_filename, source_ptrs, lang):
    """
    Will alter the source_ptrs.
    Returns WDitems (Q->WD), WPnames (name-WD), common_name_Qs (Q->Q)
    """
    WDitems = {}
    WPnames = {}
    common_name_Qs = {}
    sum_info = collections.defaultdict(int)

    (
        Q_to_WD,
        WPname_to_WD,
        src_to_WD,
        replace_Q,
        info,
    ) = OTT_popularity_mapping.wikidata_info(bz2_filename, source_ptrs, lang)

    WDitems.update(Q_to_WD)
    WPnames.update(WPname_to_WD)
    common_name_Qs.update(replace_Q)
    # Add 'wd' item to source_ptrs
    for src, ids in src_to_WD.items():
        for src_id, WD in ids.items():
            source_ptrs[src][src_id]["wd"] = WD
    for k, v in info.items():
        sum_info[k] += v

    logger.info(
        f"✔ {len(WDitems)} wikidata matches, of which "
        f"{sum_info['n_eol']} have EOL ids, {sum_info['n_iucn']} have IUCN ids, "
        f"{sum_info['n_ipni']} have IPNI, and {len(WPnames)} "
        f"({(len(WPnames)/len(WDitems)*100):.2f}%) have titles that exist on "
        f"{lang}.wikipedia. Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
    )
    return WDitems, WPnames, common_name_Qs


def set_wikipedia_pageviews(filenames, WPnames, lang):
    names_found = 0
    for fn in filenames:
        WPnames_views = OTT_popularity_mapping.pageviews_for_titles(fn, set(WPnames.keys()), lang)
        for name, n_views in WPnames_views.items():
            if not hasattr(WPnames[name], "pageviews"):
                names_found += 1
                WPnames[name].pageviews = []
            WPnames[name].pageviews.append(n_views)
    logger.info(
        f" ✔ Of {len(WPnames)} WikiData taxon entries, {names_found} "
        f"({(names_found/len(WPnames) * 100):.2f}%) have pageview data for '{lang}' in "
        f"{len(filenames)} files. Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
    )


def supplement_from_wikidata(OTT_ptrs):
    """
    If no OTT_ptrs[OTTid]['eol'] exists, but there is an
    OTT_ptrs[OTTid]['wd']['initial_wiki_item']['EoL'] then put this into
    OTT_ptrs[OTTid]['eol']
    Similarly for IPNI (although this is currently unpopulated)
    """
    EOLalready = n_eol = n_ipni = n = 0
    for data in OTT_ptrs.values():
        n += 1
        if data.get("eol") is None:
            try:
                data["eol"] = int(data["wd"].EoL)
                n_eol += 1
            except (AttributeError, KeyError, TypeError, ValueError):
                pass
        else:
            EOLalready += 1
        if data.get("ipni") is None:
            try:
                data["ipni"] = int(data["wd"].ipni)
                n_ipni += 1
            except (AttributeError, KeyError, TypeError, ValueError):
                pass
    logger.info(
        f"✔ Out of {n} OTT taxa, {EOLalready} ({(EOLalready/n * 100):.2f}%) already "
        f"have EOL ids from the EOL file. Supplementing these with {n_eol} EOL ids from "
        f"wikidata gives a coverage of {((EOLalready + n_eol)/n * 100):.1f} %."
        + (f" An addition {n_ipni} IPNI identifiers added via wikidata" if n_ipni else "")
    )


def add_eol_IDs_from_EOL_table_dump(source_ptrs, identifiers_filename, source_mapping):
    used = 0
    EOL2OTT = {v: k for k, v in source_mapping.items()}
    with open_file_based_on_extension(identifiers_filename, "rt") as identifiers_file:
        reader = csv.DictReader(identifiers_file)
        for EOLrow in reader:
            if reader.line_num % 1000000 == 0:
                logger.info(
                    f"... {reader.line_num} rows read, {used} used,  "
                    f"mem usage {OTT_popularity_mapping.mem():.1f} Mb"
                )
            provider = int(EOLrow["resource_id"])
            if provider in EOL2OTT:
                src = source_ptrs[EOL2OTT[provider]]
                if EOL2OTT[provider] == "gbif" and not EOLrow["resource_pk"].isdigit():
                    # The EoL file has duplicate (non numeric) IDs for GBIF: ignore these
                    continue
                providerid = EOLrow["resource_pk"]
                EOLid = int(EOLrow["page_id"])
                try:
                    if int(providerid) in src:
                        used += 1
                        src[int(providerid)]["EoL"] = EOLid
                except ValueError:
                    if providerid in src:
                        used += 1
                        src[providerid]["EoL"] = EOLid
        logger.info(
            f"✔ Matched {used} EoL entries in the EoL identifiers file. "
            f"Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
        )


def identify_best_EoLdata(OTT_ptrs, sources):
    """
    Each OTT number may point to several EoL entries, one for the NCBI number,
    another for the WORMS number, etc etc. Hopefully these will be the same entry,
    but they may not be. If they are different we need to choose the best one
    to use. We take the one with the most sources supporting this entry:
    if there is a tie, we take the lowest, as recommended by JRice from EoL
    """
    validOTTs = OTTs_with_EOLmatch = dups = 0
    for OTTid, data in OTT_ptrs.items():
        validOTTs += 1
        choose = {}
        for src in sources:
            if src in data["sources"] and data["sources"][src] is not None:
                if "EoL" in data["sources"][src]:
                    EOLid = int(data["sources"][src]["EoL"])
                    if EOLid not in choose:
                        choose[EOLid] = []
                    choose[EOLid] += [src]
        if len(choose) == 0:
            data["eol"] = None
        else:
            OTTs_with_EOLmatch += 1
            errstr = None
            if len(choose) > 1:
                # weed out those EOLids with the least support.
                errstr = f"More than one EoL ID {choose} for taxon OTT: {OTTid}"
                dups += 1
                max_refs = max([len(choose[i]) for i in choose])
                choose = [EOLid for EOLid in choose if len(choose[EOLid]) == max_refs]
            best = min(choose)
            data["eol"] = best
            if errstr:
                logger.debug(f" {errstr}, chosen {best}")
    logger.info(
        f" ✔ Of {validOTTs} OpenTree taxa, {OTTs_with_EOLmatch} "
        f"({OTTs_with_EOLmatch / validOTTs * 100:.2f}%) have EoL entries in the EoL "
        f"identifiers file, and {dups} have multiple possible EOL ids. "
        f"Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
    )


def populate_iucn(OTT_ptrs, identifiers_filename, verbosity=0, iucn_num=5):
    """
    Port the IUCN number from both EoL and Wikidata, and keep both if there is a conflict
    """
    used = 0

    eol_mapping = {}  # to store eol=>iucn
    for OTTid, data in OTT_ptrs.items():
        if "eol" in data:
            if data["eol"] in eol_mapping:
                eol_mapping[data["eol"]].append(OTTid)
            else:
                eol_mapping[data["eol"]] = [OTTid]

    with open_file_based_on_extension(identifiers_filename, "rt") as identifiers_file:
        reader = csv.DictReader(identifiers_file)
        for EOLrow in reader:
            if reader.line_num % 1000000 == 0:
                logger.info(
                    f" - {reader.line_num} rows read, {used} used. " f"Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
                )
            if int(EOLrow["resource_id"]) == iucn_num and EOLrow["resource_pk"].isdigit():
                # there are lots of non-species IUCN rows with pk == str (e.g. Animalia)
                try:
                    for ott in eol_mapping[int(EOLrow["page_id"])]:
                        OTT_ptrs[ott]["iucn"] = EOLrow["resource_pk"]
                        used += 1
                except LookupError:
                    pass  # no equivalent eol id in eol_mapping
        logger.info(
            f" > matched {used} IUCN entries in the EoL identifiers file. "
            f"Mem usage {OTT_popularity_mapping.mem():.1f} Mb"
        )

    # now go through and double-check against IUCN stored on wikidata
    for OTTid, data in OTT_ptrs.items():
        try:
            wd_iucn = str(int(data["wd"].iucn))
            if "iucn" not in data:
                data["iucn"] = wd_iucn
                used += 1
            else:
                if wd_iucn not in data["iucn"].split("|"):
                    data["iucn"] += "|" + wd_iucn
                logger.debug(
                    f' conflicting IUCN IDs for OTT {OTTid}: EoL = {data["iucn"]} '
                    f'(via http://eol.org/pages/{data["eol"]}), wikidata = '
                    f'{wd_iucn} (via http://http://wikidata.org/wiki/Q{data["wd"].Q}).'
                )
        except ValueError:
            logger.warning(f" Cannot convert wikidata IUCN ID {data['wd'].iucn} to integer.")
        except (KeyError, AttributeError):
            pass  # can't find a wd instance or an iucn within the wd instance. Oh well.

    logger.info(f" > Increased IUCN coverage to {used} taxa using wikidata")


def parse_sourceinfo(sourceinfo):
    """Deparse a sourceinfo string, e.g. "ncbi:1274384,gbif:8094325", into a dict of IDs"""
    out = {}
    for i in sourceinfo.split(","):
        if not i:
            continue
        k, v = i.split(":", 1)
        out[k] = int(v) if v.isdigit() else v
    return out


def read_ot_taxonomy(path="./data/OpenTree/v16.1/taxonomy.tsv"):
    """Yield each row of an OpenTree taxonomy file as a dict keyed by header.

    Fields are separated by ``\\t|\\t`` and each line ends with a trailing
    ``\\t|\\t``, so this is not parseable as a plain TSV.
    """
    with open(path, encoding="utf-8") as f:
        header = next(f).rstrip("\n").split("\t|\t")[:-1]
        for line in f:
            fields = line.rstrip("\n").split("\t|\t")[:-1]
            out = dict(zip(header, fields))

            out["uid"] = int(out["uid"])
            out["parent_uid"] = None if out["parent_uid"] == "" else int(out["parent_uid"])
            out["sourceinfo"] = parse_sourceinfo(out["sourceinfo"])

            yield out


def read_extra_source_file(path):
    """Yield each row of an extra source file, in the same form as read_ot_taxonomy().

    Unlike the OpenTree taxonomy this is a plain TSV, requiring only "uid" and
    "sourceinfo" columns. The uid need not be a number (e.g. "mrcaott409215ott616649").
    """
    try:
        with open(path, encoding="utf-8", newline="") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                out = dict(row)
                out["uid"] = int(row["uid"]) if row["uid"].isdigit() else row["uid"]
                out["sourceinfo"] = parse_sourceinfo(row["sourceinfo"])
                yield out
    except FileNotFoundError:
        logger.warning(f" Extra source file '{path}' not found, so ignored")


def add_taxon_sources(OTT_ptrs, source_ptrs, ott, sourceinfo, rank=None):
    """
    Point OTT_ptrs[ott] at an entry in source_ptrs for each source in sourceinfo,
    adding the OTT if not already there, and overwriting any existing source of
    the same name.
    """
    ott_data = OTT_ptrs.setdefault(ott, {"ott": ott, "sources": {}})
    if rank is not None:
        ott_data["rank"] = rank

    has_ncbi = False
    for src in reversed(sourceinfo.keys()):
        # NB: look at sources in reverse order, overwriting, so 1st ones take priority
        src_id = sourceinfo[src]
        if src == "ncbi":
            has_ncbi = True
        elif not has_ncbi and src == "ncbi_silva":
            # only use the ncbi_via_silva id if no 'normal' ncbi already set
            src = "ncbi"
        source_ptrs.setdefault(src, {})[src_id] = {"id": src_id}
        ott_data["sources"][src] = source_ptrs[src][src_id]


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--OpenTreeTaxonomy",
        default="data/OpenTree/v16.1/taxonomy.tsv",
        help="The OpenTree taxonomy.tsv file, from http://files.opentreeoflife.org/ott/",
    )
    parser.add_argument(
        "--wikidataDumpFile",
        default="data/filtered/OneZoom_latest-all.json",
        help=(
            "The very large wikidata JSON dump, "
            "from https://dumps.wikimedia.org/wikidatawiki/entities/ (latest-all.json.bz2)."
            "A filtered version can be used for faster processing."
        ),
    )
    parser.add_argument(
        "--wikilang",
        default="en",
        help=(
            'The language wikipedia to check for popularity, e.g. "en". '
            "Where there are multiple Wikidata items for a taxon "
            "(e.g. one under the common name, one under the scientific name), "
            "then we also default to using the WD item with the sitelink in this language."
        ),
    )
    parser.add_argument(
        "--wikipediaSQLDumpFile",
        default="data/filtered/OneZoom_enwiki-latest-page.sql",
        help=(
            "The gzipped >1GB wikipedia -latest-page.sql.gz dump, "
            "from https://dumps.wikimedia.org/enwiki/latest/ (enwiki-page.sql.gz) "
        ),
    )
    parser.add_argument(
        "--wikipedia_totals_bz2_pageviews",
        default="data/filtered/pageviews/",
        help=(
            'Directory of b2zipped "totals" pageview count files, '
            "from https://dumps.wikimedia.org/other/pagecounts-ez/merged/ "
            "(e.g. pagecounts-2016-01-views-ge-5-totals.bz2, or pagecounts*totals.bz2)"
        ),
    )
    parser.add_argument(
        "--EOLidentifiers",
        default="data/filtered/OneZoom_provider_ids.csv",
        help=("EOL identifiers file, from " "https://opendata.eol.org/dataset/identifiers-csv-gz"),
    )
    parser.add_argument(
        "--extra_source_file",
        default=None,
        type=str,
        help=(
            "An optional additional file to supplement the taxonomy.tsv file, "
            "providing additional mappings from OTTs to source ids (useful for overriding). "
            'The first line should be a header contining "uid" and "sourceinfo" column '
            "headers, similar to those in the taxonomy.tsv file. NB the OTT can be a "
            'number, or an ID of the form "mrcaott409215ott616649").'
        ),
    )
    parser.add_argument(
        "-o",
        type=argparse.FileType("w"),
        default="-",
        help=("File to output CSV OTT map to"),
    )
    parser.add_argument(
        "--skip_popularity",
        action="store_true",
        help="Skip popularity calculations (no wikipedia SQL dump or pageviews required)",
    )
    args = parse_args_and_add_logging_switch(parser)

    # Generate both OTT_ptrs / source_ptrs from taxonomy
    # Replaces get_OTT_list & OTT_popularity_mapping.create_from_taxonomy respectively
    logger.info("Generating OTT_ptrs / source_ptrs from taxonomy")
    OTT_ptrs = {}
    source_ptrs = {}
    for r in read_ot_taxonomy(args.OpenTreeTaxonomy):
        add_taxon_sources(OTT_ptrs, source_ptrs, r["uid"], r["sourceinfo"], r["rank"])

    if args.extra_source_file is not None:
        logger.info(f"Supplementing source IDs from {args.extra_source_file}")
        extra_otts = 0
        for r in read_extra_source_file(args.extra_source_file):
            add_taxon_sources(OTT_ptrs, source_ptrs, r["uid"], r["sourceinfo"], r.get("rank"))
            extra_otts += 1
        logger.info(f"✔ {extra_otts} OTTs supplemented from {args.extra_source_file}")

    eol_sources = {
        "ncbi": 676,
        "worms": 459,
        "gbif": 767,
    }  # update when EoL has harvested index fungorum & IRMNG
    add_eol_IDs_from_EOL_table_dump(source_ptrs, args.EOLidentifiers, eol_sources)
    identify_best_EoLdata(OTT_ptrs, eol_sources)

    map_wiki_info(
        source_ptrs=source_ptrs,
        source_order=["ncbi", "if", "worms", "irmng", "gbif"],
        OTT_ptrs=OTT_ptrs,
        WD_filename=args.wikidataDumpFile,
        lang=args.wikilang,
        WP_SQL_filename=(None if args.skip_popularity else args.wikipediaSQLDumpFile),
        WP_pageviews_filenames=(
            None if args.skip_popularity else glob.glob(os.path.join(args.wikipedia_totals_bz2_pageviews, "*"))
        ),
    )
    populate_iucn(OTT_ptrs, args.EOLidentifiers)

    # Write collated data out into CSV format
    writer = csv.writer(args.o, dialect="excel")
    writer.writerow(
        (
            "ott",
            "wikidata",
            "wikipedia_lang_flag",
            "iucn",
            "eol",
            "rank",
            "raw_popularity",
            "ncbi",
            "ifung",
            "worms",
            "irmng",
            "gbif",
            "ipni",
        )
    )
    for o in OTT_ptrs.values():
        writer.writerow(
            (
                o["ott"],
                o.get("wd", {}).get("Q"),
                o.get("wd", {}).get("wikipedia_lang_flag"),
                o.get("iucn"),
                o.get("eol"),
                o.get("rank"),
                o.get("wd", {}).get("raw_popularity"),
                o["sources"].get("ncbi", {}).get("id"),
                o["sources"].get("ifung", {}).get("id"),
                o["sources"].get("worms", {}).get("id"),
                o["sources"].get("irmng", {}).get("id"),
                o["sources"].get("gbif", {}).get("id"),
                o.get("ipni"),
            )
        )
    args.o.close()


def read_taxon_map(path):
    """Read a taxon map CSV (as written by :func:`main`) into a dict keyed by ott.

    Empty fields become ``None``. Numeric fields are converted to ``int`` or
    ``float``; ``iucn`` is left as a string because multiple values may be
    joined with ``|``. Source IDs (``ncbi``, ``ifung``, ``worms``, ``irmng``,
    ``gbif``) are converted to ``int`` where possible and otherwise left as
    strings.
    """
    int_fields = ("ott", "wikidata", "wikipedia_lang_flag", "eol", "ipni")
    float_fields = ("raw_popularity",)
    source_fields = ("ncbi", "ifung", "worms", "irmng", "gbif")
    out = {}
    with open(path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, dialect="excel")
        for row in reader:
            r = {k: (v if v != "" else None) for k, v in row.items()}
            for k in int_fields:
                if r.get(k) is not None:
                    r[k] = int(r[k])
            for k in float_fields:
                if r.get(k) is not None:
                    r[k] = float(r[k])
            for k in source_fields:
                if r.get(k) is not None and r[k].isdigit():
                    r[k] = int(r[k])
            out[r["ott"]] = r
    return out
