"""
Splice together a set of trees using OZ inclusion syntax
"""

import argparse
import json
import logging

from dated_complete_tree import tree_fixing

from ..date_tree import date_tree
from ..taxon_mapping_and_popularity.taxon_map import read_taxon_map
from ..utilities.debug_util import parse_args_and_add_logging_switch
from .step_graft import graft_extract_ot_subtrees, graft_tree
from .step_jsnewick import jsnewick_brief_newick, jsnewick_cutpositionmap_binary, jsnewick_cutpositionmap_polytomy
from .step_output import (
    output_add_prop_ids,
    output_jssource,
    output_mysqlexport,
    output_proparray,
)
from .step_parse import parse_bespoke_trees, parse_ot_orphans
from .step_popularity import popularity_add_prop, popularity_add_rank
from .step_taxon import taxon_add_prop
from .step_tidy import tidy_clear_conflicting_dates_topdown, tidy_infill_dates_bottomup

logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--bespoke_dir",
        help=("Directory containing bespoke trees, including Base.PHY, the root"),
    )
    parser.add_argument(
        "--orphan_dir",
        help=("Directory containing orphan OpenTree subtrees"),
    )
    parser.add_argument(
        "--opentree",
        help=("Newick tree with OpenTree"),
    )
    parser.add_argument(
        "--taxon_map",
        default="data/taxon_map.csv",
        help=("Taxon map CSV as generated by taxon_mapping_and_popularity.taxon_map"),
    )
    parser.add_argument(
        "--out_dir",
        default="data/out",
        help=("Directory to write output files to"),
    )
    args = parse_args_and_add_logging_switch(parser)

    logger.info("Parse & graft bespoke tree together")
    base_t, bespoke_ts = parse_bespoke_trees(args.bespoke_dir)
    missing_inclusions = graft_tree(base_t, additional_trees=bespoke_ts, prefer_subtree_name=True)

    logger.info("Random resoution of polytomies for bespoke trees")
    # https://etetoolkit.org/docs/latest/reference/reference_tree.html#ete3.TreeNode.resolve_polytomy
    # NB: Doesn't shuffle children like the DendroPy equivalent, but given a fixed seed do we care?
    base_t.resolve_polytomy()

    logger.info("Resolve branch lengths to dates bottom-up. Remove (or not care about) branch lengths")
    tidy_infill_dates_bottomup(base_t)

    logger.info("Top-down conflict resolution in bespoke tree, delete entries that conflict with higher ages")
    tidy_clear_conflicting_dates_topdown(base_t)

    logger.info("Graft OT subtrees onto our trees. Already polytomy-resolved & date pins from chronosynth applied")
    opentree_ts = graft_extract_ot_subtrees(date_tree.nwk_read(args.opentree), missing_inclusions)
    opentree_ts.update(parse_ot_orphans(args.orphan_dir, missing_inclusions))
    missing_inclusions = graft_tree(
        base_t, additional_trees=opentree_ts, prefer_subtree_name=False, disable_recursion=True
    )
    for i in missing_inclusions:
        logger.error(f"No subtree found for {i}")

    logger.info("Attach taxon information to nodes")
    taxon_add_prop(base_t, read_taxon_map(args.taxon_map))

    logger.info(
        "Popularity calculations for entire tree (including any remaining subspecies from bespoke tree, "
        "Jonathan's will have them already removed) (stop caring about polytomy vs. popularity calculations, "
        "and just apply them post-resolution). Apply popularity based on OTT -> popularity map, percolate "
        "using existing rules (which preserves popularity from removed subspecies)"
    )
    popularity_add_prop(base_t)

    logger.info("Remove subspecies (now popularity has percolated)")
    # tidy_remove_subspecies(base_t)

    logger.info(
        "Top-down conflict resolution. If there's conflict with higher ages, remove ages until conflict goes away"
    )
    tidy_clear_conflicting_dates_topdown(base_t)

    logger.info("Remove unary nodes (they are likely uninteresting, and make a mess of the tree rendering)")
    tree_fixing.delete_one_child_nodes(base_t)

    logger.info("Re-interpoltate missing dates")
    # interpolate_dates(base_t)

    logger.info("Rank popularities, post-node removal")
    popularity_add_rank(base_t)

    logging.info("ladderizing tree (groups with fewer leaves first)")
    # warning: ladderize ascending is needed for the short OZ newick-like form
    base_t.ladderize(topological=False, reverse=False)

    logger.info("Add properies to tree")
    pass

    logger.info("Output MySQL CSV files")
    output_add_prop_ids(base_t)
    output_mysqlexport(base_t, args.out_dir)

    logger.info("Output JS newick / cut position map")
    output_jssource(
        base_t,
        args.out_dir,
        "completetree.js",
        dict(
            rawData=jsnewick_brief_newick(base_t, polytomy_braces="{}"),
        ),
    )
    cutmap_threshold = 10000
    output_jssource(
        base_t,
        args.out_dir,
        "cut_position_map.js",
        dict(
            # NB: For legacy reasons the variable contains a JSON string, not JSON
            cut_position_map_json_str=json.dumps(jsnewick_cutpositionmap_binary(base_t, threshold=cutmap_threshold)),
            polytomy_cut_position_map_json_str=json.dumps(
                jsnewick_cutpositionmap_polytomy(base_t, threshold=cutmap_threshold)
            ),
            threshold=cutmap_threshold,
        ),
    )


if __name__ == "__main__":
    main()
